# Generated by Django 5.1.2 on 2024-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, null=NameError),
            preserve_default=NameError,
        ),
    ]
